version: '3.4'

services:
    web:
      image: nginx:latest
      ports:
        - "80:80"
      volumes:
        - .:/var/www
        - ./nginx.conf:/etc/nginx/conf.d/default.conf
      links:
        - php

    php:
      build: .
      volumes: 
        - .:/var/www
      links:
        - mysql

    mysql:
      image: mysql:5.7
      volumes:
        - ./.data:/var/lib/mysql
      ports:
        - "3306:3306"
      environment: 
        - MYSQL_ROOT_PASSWORD=password